name: Build artifacts

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    name: Build artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.12
          cache: true
          cache-dependency-path: pdm.lock
      - name: Install dependencies
        run: pdm install
      - name: Run CI
        run: pdm run ci
      - name: Build bdists_wheel
        run: |-
          pdm build --config-setting="--python-tag=cp312" `
            --config-setting="--py-limited-api=cp312" `
            --config-setting="--plat-name=win_amd64"
        shell: pwsh
      - uses: actions/upload-artifact@v4
        with:
          name: bdists_wheel
          path: dist/
